### PR TITLE
Line Endings

### PR DESCRIPTION
**Pull request by ajmueller**
- Adds line ending standards to `.editorconfig`.
- Adds final newline characters to all files.
- Adds contribution guidelines outlining the usage of the `.editorconfig` file as well as noting to always shrinkwrap dependencies.

### CODE REVIEW

**Comment by bmorelli25** [comment]
Looks great!

**Comment by ajmueller** [comment]
@bmorelli25 thanks!  One more random question: how do you feel about the `indent_size` being set to 4?  That's my personal preference, but I know everyone is different.  Two spaces seems to dominate the open source community and I personally can't stand it (the tabs vs. spaces debate will seemingly never end...).  I'm on the side of tabs because it allows all developers to choose their tab size, but with this setting it forces the spacing to be set to 4, essentially negating the benefit of tabs.

This may be pedantic, but I want to make sure the project is welcoming to all.

**Comment by bmorelli25** [comment]
It is a minute detail - but I (and I'm sure everyone else) appreciate how open you are to discussion on even these smaller details. 

Anyway, yes! Four spaces for `indent_size` is a-ok with me

**Comment by ajmueller** [comment]
@bmorelli25 great!  This has been merged.

**Pull request merged**
